### Get Instristic Feature Matrix

Apply Funk SVD Maxtrix Decomposition

In [ ]:
import pandas as pd
Gamma_Matrix = pd.read_csv('../csv_files/manager_fund.csv')
Gamma_Matrix

Unnamed: 0        name  000001.SZ  ...  688599.SH  688600.SH  688981.SH
0              0  HAN YILING   0.025594  ...   0.000000   0.000000   0.000624
1              1    TIANHUAN   0.005490  ...   0.000000   0.000096   0.000000
2              2          丁尧   0.003961  ...   0.000000   0.000015   0.000000
3              3          丁玥   0.002389  ...   0.000000   0.000111   0.000000
4              4          丁琳   0.000000  ...   0.000000   0.000000   0.000000
...          ...         ...        ...  ...        ...        ...        ...
1079        1079         黎海威   0.000170  ...   0.000000   0.000004   0.000000
1080        1080          黎莹   0.000000  ...   0.000000   0.000022   0.000000
1081        1081         龙宇飞   0.002765  ...   0.000065   0.000000   0.005528
1082        1082         龙昌伦   0.009264  ...   0.000000   0.000000   0.000000
1083        1083          龚炜   0.000000  ...   0.000000   0.000000   0.000000

[1084 rows x 3979 columns]

In [ ]:
Gamma_Matrix.columns.values.tolist()

['Unnamed: 0',
 'name',
 '000001.SZ',
 '000002.SZ',
 '000004.SZ',
 '000005.SZ',
 '000006.SZ',
 '000007.SZ',
 '000008.SZ',
 '000009.SZ',
 '000010.SZ',
 '000011.SZ',
 '000012.SZ',
 '000014.SZ',
 '000016.SZ',
 '000017.SZ',
 '000018.SZ',
 '000019.SZ',
 '000020.SZ',
 '000021.SZ',
 '000022.SZ',
 '000023.SZ',
 '000025.SZ',
 '000026.SZ',
 '000027.SZ',
 '000028.SZ',
 '000029.SZ',
 '000030.SZ',
 '000031.SZ',
 '000032.SZ',
 '000034.SZ',
 '000035.SZ',
 '000036.SZ',
 '000037.SZ',
 '000038.SZ',
 '000039.SZ',
 '000040.SZ',
 '000042.SZ',
 '000043.SZ',
 '000045.SZ',
 '000046.SZ',
 '000048.SZ',
 '000049.SZ',
 '000050.SZ',
 '000055.SZ',
 '000056.SZ',
 '000058.SZ',
 '000059.SZ',
 '000060.SZ',
 '000061.SZ',
 '000062.SZ',
 '000063.SZ',
 '000065.SZ',
 '000066.SZ',
 '000068.SZ',
 '000069.SZ',
 '000070.SZ',
 '000078.SZ',
 '000088.SZ',
 '000089.SZ',
 '000090.SZ',
 '000096.SZ',
 '000099.SZ',
 '000100.SZ',
 '000150.SZ',
 '000151.SZ',
 '000153.SZ',
 '000155.SZ',
 '000156.SZ',
 '000157.SZ',
 '000158.SZ',
 '000159.S

In [ ]:
Gamma_Matrix.drop(columns = ['Unnamed: 0','name'],inplace = True)
Gamma_Matrix

000001.SZ  000002.SZ  000004.SZ  ...  688599.SH  688600.SH  688981.SH
0      0.025594   0.004036        0.0  ...   0.000000   0.000000   0.000624
1      0.005490   0.003535        0.0  ...   0.000000   0.000096   0.000000
2      0.003961   0.007806        0.0  ...   0.000000   0.000015   0.000000
3      0.002389   0.032061        0.0  ...   0.000000   0.000111   0.000000
4      0.000000   0.005710        0.0  ...   0.000000   0.000000   0.000000
...         ...        ...        ...  ...        ...        ...        ...
1079   0.000170   0.001187        0.0  ...   0.000000   0.000004   0.000000
1080   0.000000   0.020501        0.0  ...   0.000000   0.000022   0.000000
1081   0.002765   0.004907        0.0  ...   0.000065   0.000000   0.005528
1082   0.009264   0.004177        0.0  ...   0.000000   0.000000   0.000000
1083   0.000000   0.000000        0.0  ...   0.000000   0.000000   0.000000

[1084 rows x 3977 columns]

In [ ]:
Gamma_Matrix.to_csv("../csv_files/Gamma_Matrix_manager.csv", index=False)

In [ ]:
Gamma_Matrix=pd.read_csv('../csv_files/Gamma_Matrix_manager.csv')
Gamma_Matrix

000001.SZ  000002.SZ  000004.SZ  ...  688599.SH  688600.SH  688981.SH
0      0.025594   0.004036        0.0  ...   0.000000   0.000000   0.000624
1      0.005490   0.003535        0.0  ...   0.000000   0.000096   0.000000
2      0.003961   0.007806        0.0  ...   0.000000   0.000015   0.000000
3      0.002389   0.032061        0.0  ...   0.000000   0.000111   0.000000
4      0.000000   0.005710        0.0  ...   0.000000   0.000000   0.000000
...         ...        ...        ...  ...        ...        ...        ...
1079   0.000170   0.001187        0.0  ...   0.000000   0.000004   0.000000
1080   0.000000   0.020501        0.0  ...   0.000000   0.000022   0.000000
1081   0.002765   0.004907        0.0  ...   0.000065   0.000000   0.005528
1082   0.009264   0.004177        0.0  ...   0.000000   0.000000   0.000000
1083   0.000000   0.000000        0.0  ...   0.000000   0.000000   0.000000

[1084 rows x 3977 columns]

In [ ]:
Gamma_numpy=Gamma_Matrix.to_numpy()

In [ ]:
Gamma_numpy

array([[2.55936920e-02, 4.03641704e-03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 6.24257839e-04],
       [5.49021953e-03, 3.53456045e-03, 0.00000000e+00, ...,
        0.00000000e+00, 9.59338536e-05, 0.00000000e+00],
       [3.96141948e-03, 7.80606077e-03, 0.00000000e+00, ...,
        0.00000000e+00, 1.53528220e-05, 0.00000000e+00],
       ...,
       [2.76468821e-03, 4.90743452e-03, 0.00000000e+00, ...,
        6.50037989e-05, 0.00000000e+00, 5.52765206e-03],
       [9.26379200e-03, 4.17662177e-03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [ ]:
import numpy as np

In [ ]:
iter=[]

In [ ]:
def FunkSVD(ratings_mat, latent_features=10, learning_rate=0.0001, iters=20, random_seed=52, verbose=True):
    '''
    This function performs matrix factorization using a basic form of FunkSVD with no regularization
    
    INPUT:
    ratings_mat - (numpy array) a matrix with users as rows, offers (subtype) as columns, and ratings as values
    latent_features - (int) the number of latent features used
    learning_rate - (float) the learning rate 
    iters - (int) the number of iterations
    
    OUTPUT:
    user_mat - (numpy array) a user by latent feature matrix
    offer_mat - (numpy array) a latent feature by offer matrix
    '''
    
    # Set up useful values to be used through the rest of the function
    n_users = ratings_mat.shape[0]
    n_offers = ratings_mat.shape[1]
    num_ratings = np.count_nonzero(~np.isnan(ratings_mat))
    
    # initialize the user and offer matrices with random values
    np.random.seed (random_seed)
    user_mat = np.random.rand(n_users, latent_features)
    offer_mat = np.random.rand(latent_features, n_offers)
    
    # initialize sse at 0 for first iteration
    sse_accum = 0
    
    # header for running results
    if verbose:
        print("Optimizaiton Statistics")
        print("Iterations | Mean Squared Error ")
    
    # for each iteration
    for iteration in range(iters):

        # update our sse
        old_sse = sse_accum
        sse_accum = 0
        
        # For each user-offer pair
        for i in range(n_users):
            for j in range(n_offers):
                
                # if the rating exists
                if (ratings_mat[i, j] == 0)|(ratings_mat[i, j] == 1):
                    
                    # compute the error as the actual minus the dot product of the user and offer latent features
                    diff = ratings_mat[i, j] - np.dot(user_mat[i, :], offer_mat[:, j])
                    
                    # Keep track of the sum of squared errors for the matrix
                    sse_accum += diff**2
                    
                    # update the values in each matrix in the direction of the gradient
                    for k in range(latent_features):
                        user_mat[i, k] += learning_rate * (2*diff*offer_mat[k, j])
                        offer_mat[k, j] += learning_rate * (2*diff*user_mat[i, k])
        iter.append((user_mat,offer_mat))
        # print results for iteration
        if verbose: 
            print("%d \t\t %f" % (iteration+1, sse_accum / num_ratings))
    
    return user_mat, offer_mat 

In [ ]:
user_mat, offer_mat=FunkSVD(Gamma_numpy, latent_features=10, learning_rate=0.0001, iters=20, random_seed=52, verbose=True)

Optimizaiton Statistics
Iterations | Mean Squared Error 
1 		 1.608606
2 		 0.108911
3 		 0.044546
4 		 0.035234
5 		 0.030558
6 		 0.026859
7 		 0.023729
8 		 0.021041
9 		 0.018718
10 		 0.016698
11 		 0.014933
12 		 0.013384
13 		 0.012021
14 		 0.010815
15 		 0.009747
16 		 0.008797
17 		 0.007951
18 		 0.007195
19 		 0.006517
20 		 0.005910


In [ ]:
user_mat

array([[ 0.12764594, -0.17687494, -0.10817565, ...,  0.18006481,
         0.18879977, -0.00045114],
       [-0.00799539,  0.04321826,  0.03177371, ...,  0.00219329,
        -0.11042051,  0.07348363],
       [-0.03333058, -0.14213909, -0.0574307 , ...,  0.12140857,
         0.11316353, -0.04069901],
       ...,
       [-0.09942288,  0.17072028, -0.11873703, ..., -0.04512358,
         0.0624432 ,  0.08084589],
       [ 0.15554011, -0.10357584, -0.02015343, ...,  0.14345317,
        -0.22735242,  0.07374146],
       [-0.13969048,  0.16169733,  0.13360578, ...,  0.10771433,
         0.08517022,  0.03131007]])

In [ ]:
offer_mat

array([[ 0.65653233,  0.5336017 ,  0.18571604, ...,  0.26924659,
         0.10638469,  0.35881938],
       [-0.06258072,  0.0959632 ,  0.67801651, ...,  0.71138439,
         0.31911253,  0.39045791],
       [ 0.16008804,  0.29366774,  0.3985514 , ...,  0.66792231,
         0.33233821,  0.67643802],
       ...,
       [ 0.65374034,  0.16850926,  0.22253263, ...,  0.06163415,
         0.4964009 ,  0.28071002],
       [ 0.73517441,  0.58576625,  0.09073953, ...,  0.14238389,
         0.48681274,  0.74283392],
       [ 0.54286725,  0.488633  ,  0.12651469, ...,  0.36628239,
         0.75366144,  0.51897186]])

In [ ]:
DataFrame(user_mat).to_csv("../csv_files/manager_intrisic.csv", index=False)
DataFrame(offer_mat).to_csv("../csv_files/stock_intrisic.csv", index=False)

In [ ]:
user_mat=iter20[0]
user_mat

'[[ 0.12764594 -0.17687494 -0.10817565 ...  0.18006481  0.18879977\n  -0.00045114]\n [-0.00799539  0.04321826  0.03177371 ...  0.00219329 -0.11042051\n   0.07348363]\n [-0.03333058 -0.14213909 -0.0574307  ...  0.12140857  0.11316353\n  -0.04069901]\n ...\n [-0.09942288  0.17072028 -0.11873703 ... -0.04512358  0.0624432\n   0.08084589]\n [ 0.15554011 -0.10357584 -0.02015343 ...  0.14345317 -0.22735242\n   0.07374146]\n [-0.13969048  0.16169733  0.13360578 ...  0.10771433  0.08517022\n   0.03131007]]'

In [ ]:
offer_mat=iteration_20[19][1]
offer_mat

array([[ 0.25725187,  0.11305972,  0.00484216, ...,  0.15431312,
         0.4295725 ,  0.22659998],
       [ 0.24695858,  0.33478182, -0.04101804, ...,  0.4388654 ,
         0.08277616,  0.39166821],
       [-0.18892353,  0.29041712, -0.0645813 , ...,  0.53095235,
         0.41482708,  0.32870584],
       ...,
       [ 0.3172446 ,  0.00599257, -0.13042732, ...,  0.58205978,
         0.4213078 ,  0.34942159],
       [ 0.12705274, -0.09478701,  0.28765489, ...,  0.54436715,
         0.23182803,  0.30708569],
       [ 0.00773352,  0.40102346, -0.02928691, ...,  0.05916632,
         0.48837008,  0.34488647]])

In [ ]:
import pandas as pd
fund_manager_matrix_fea10_0056mse = pd.DataFrame(user_mat)
fund_manager_matrix_fea10_0056mse

0         1         2  ...         7         8         9
0     0.147743 -0.217537 -0.140363  ...  0.197384  0.207214  0.005465
1    -0.004533  0.049345  0.053934  ...  0.006631 -0.127014  0.090214
2    -0.041730 -0.170549 -0.073588  ...  0.137351  0.116993 -0.036344
3     0.024223  0.135056 -0.007596  ... -0.101349  0.148315 -0.184367
4    -0.007672 -0.212048  0.003123  ... -0.160773  0.141017  0.088416
...        ...       ...       ...  ...       ...       ...       ...
3977  0.145099  0.199535  0.151154  ... -0.107591 -0.173279  0.088567
3978  0.049375 -0.120812  0.090876  ... -0.132447  0.146858 -0.128212
3979  0.120171 -0.108702  0.197799  ...  0.007425 -0.063224 -0.199747
3980 -0.096565  0.148005 -0.091417  ... -0.072327 -0.014523  0.011214
3981  0.143222 -0.169812  0.046348  ...  0.146238 -0.217599 -0.075292

[3982 rows x 10 columns]

In [ ]:
stock_matrix_fea10_0056mse = pd.DataFrame(offer_mat)
stock_matrix_fea10_0056mse

0         1         2     ...      4492      4493      4494
0  0.257252  0.113060  0.004842  ...  0.154313  0.429572  0.226600
1  0.246959  0.334782 -0.041018  ...  0.438865  0.082776  0.391668
2 -0.188924  0.290417 -0.064581  ...  0.530952  0.414827  0.328706
3  0.090117  0.164472  0.007345  ...  0.387971  0.118431  0.530921
4  0.455764 -0.074736  0.002143  ...  0.243994  0.343465  0.187444
5 -0.111164 -0.019487  0.241617  ...  0.314317  0.055713  0.248331
6 -0.117810  0.018136  0.051487  ...  0.371765  0.178727  0.154487
7  0.317245  0.005993 -0.130427  ...  0.582060  0.421308  0.349422
8  0.127053 -0.094787  0.287655  ...  0.544367  0.231828  0.307086
9  0.007734  0.401023 -0.029287  ...  0.059166  0.488370  0.344886

[10 rows x 4495 columns]

In [ ]:
fund_manager_matrix_fea10_0056mse.to_csv("../csv_files/fund_manager_feature10_MSE0056.csv", index=False)
stock_matrix_fea10_0056mse.to_csv("../csv_files/stock_feature10_MSE0056.csv", index=False)